name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  embed-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: node -v

    - run: npm -v

    - name: Markdown autodocs
      uses:  dineshsonachalam/markdown-autodocs@v1.0.4