name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  embed-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: markdown-embed-code
        uses: tokusumi/markdown-embed-code@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
