name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  embed-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pip install gssapi
      - uses: tokusumi/markdown-embed-code@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
