name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  embed-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: wget https://raw.githubusercontent.com/dineshsonachalam/markdown-autodocs/master/action.py
      shell: bash

    - run: python3 action.py -repo '${{ github.repository }}' -access_token '${{ github.token }}'
      shell: bash

#    - run: npm i -g markdown-autodocs

#    - name: Markdown autodocs
#      uses:  dineshsonachalam/markdown-autodocs@v1.0.3