name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  embed-code:

    runs-on: ubuntu-latest

    steps:
#    - run: wget https://raw.githubusercontent.com/dineshsonachalam/markdown-autodocs/master/action.py
#      shell: bash
#    - run: python3 action.py -repo '${{ github.repository }}' -access_token '${{ github.token }}' -commit_author '${{ github.actor }}' -commit_user_email 'actions@github.com' -commit_message 'Apply automatic changes' -branch '${{ github.ref }}' -output_file_paths '[./README.md]' -categories '[code-block,json-to-html-table,workflow-artifact-table,markdown]'
#      shell: bash
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: v18.0.0
        cache: 'npm'

    - run: ls -la /usr/local/lib
    - run: ls -la /usr/local/lib/node_modules
    - run: ls -la /usr/local/lib/node_modules
    - run: ls -la /opt/hostedtoolcache/node

    - run: npm i -g markdown-autodocs
    - run: node --experimental-modules /opt/hostedtoolcache/node/18.0.0/x64/lib/node_modules/markdown-autodocs/index.js --help


#    - name: Markdown autodocs
#      uses:  dineshsonachalam/markdown-autodocs@v1.0.3