name: Embed code in README

on:
  pull_request:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run readmemd
      - name: check for changes
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          if git diff --exit-code --quiet; then
            echo "::set-env name=changes_exist::false"
          else
            echo "::set-env name=changes_exist::true"
          fi
      - run: ls -la
      - name: commit and push changes
        if: ${{ env.changes_exist == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "update README.md"
          git push
